# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_quo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('item_num', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=19)),
                ('uom', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=10, max_digits=19)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('quote_num', models.TextField()),
                ('tax', models.BooleanField()),
                ('tax_amt', models.DecimalField(decimal_places=5, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.Project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='line_quo',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote'),
        ),
    ]
