# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 602553)),
        ),
        migrations.AddField(
            model_name='contact',
            name='viewed',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 602553)),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='eff_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 604553)),
        ),
        migrations.AddField(
            model_name='contract',
            name='perp',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='contract',
            name='term_note',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='viewed',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 604553)),
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 605554)),
        ),
        migrations.AddField(
            model_name='note',
            name='viewed',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 605554)),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 603553)),
        ),
        migrations.AddField(
            model_name='supplier',
            name='viewed',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 11, 24, 30, 603553)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
