# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20170223_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='main_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='viewed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='viewed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='viewed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='viewed',
            field=models.DateTimeField(),
        ),
    ]
