# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('key', models.CharField(max_length=140)),
                ('value', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
        ),
    ]
