# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Line_PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('item_num', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('uom', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=10, max_digits=19)),
                ('dept_code', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('blanket', models.BooleanField()),
                ('status', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('tax', models.BooleanField()),
                ('tax_amt', models.DecimalField(decimal_places=5, max_digits=5)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('budgeted', models.BooleanField(default=False)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Cost_Center')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.Quote')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='line_po',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.PO'),
        ),
        migrations.AddField(
            model_name='line_po',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Publisher'),
        ),
    ]
