# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='line_po',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='line_po',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='po',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
