# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_auto_20170717_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='line_po',
            name='budget_code',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='line_po',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='po.Cost_Center'),
        ),
        migrations.AlterField(
            model_name='po',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='po',
            name='blanket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='po',
            name='num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='tax',
            field=models.BooleanField(default=False),
        ),
    ]
