# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_auto_20170717_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='tax_amt',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
    ]
