# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('prod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('began', models.DateTimeField()),
                ('detected', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('tz', models.CharField(max_length=3)),
                ('owner', models.TextField(null=True)),
                ('rca', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('environ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outage.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='outage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outage.Service'),
        ),
        migrations.AddField(
            model_name='outage',
            name='sev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outage.Severity'),
        ),
    ]
