# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='detected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
