# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0002_auto_20170922_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='began',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='outage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outage',
            name='rca',
            field=models.TextField(null=True),
        ),
    ]
