# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outage', '0003_auto_20170922_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='outage',
            name='auth_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
