# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0004_outage_auth_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
