# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr_contract_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Term_mo', models.IntegerField()),
                ('yr_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spend_cur_fy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spend_prev_fy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('savings_start', models.DateField()),
                ('savings_end', models.DateField()),
                ('budget_type', models.CharField(max_length=50)),
                ('cs_type', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=50)),
                ('nature', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='theo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finance',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Tracker'),
        ),
    ]
