# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170202_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='finance',
            name='budget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Budget'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='confidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Confidence'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='cs_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.CSType'),
        ),
    ]
