# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170202_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
