# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170202_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='Term_mo',
            new_name='term_mo',
        ),
    ]
