# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170202_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='savings_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='spend_cur_fy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='spend_prev_fy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
