# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170202_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='budget_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Budget'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Confidence'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='cs_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.CSType'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='savings_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
