# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20170203_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
